# Generated by Django 2.0.2 on 2018-03-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('genre2', models.CharField(max_length=128)),
                ('date', models.PositiveIntegerField()),
                ('start_time', models.PositiveIntegerField()),
                ('end_time', models.PositiveIntegerField()),
                ('cate1', models.CharField(max_length=128, null=True)),
                ('url', models.URLField(max_length=2048)),
                ('img', models.URLField(max_length=2048)),
                ('price', models.PositiveIntegerField()),
                ('org_price', models.PositiveIntegerField()),
            ],
        ),
    ]
